### PR TITLE
Merge key change code

### PR DESCRIPTION
**Pull request by masomel**

### CODE REVIEW

**Comment by arlolra** [comment]
That doesn't look right.

**Comment by masomel** [comment]
What doesn't look right? I'm still fixing some quirks that happened when I rebased the branch from our internal repo.

**Comment by arlolra** [comment]
The merged conflict markers,

```
<<<<<<< HEAD
...
=======
...
>>>>>>> Adding the new files
```

**Comment by arlolra** [comment]
But yeah, looks like you've cleaned up the bad merge. Sorry for the noise.

**Comment by masomel** [comment]
No worries, I'm glad somebody else is looking at the code, too!

**Pull request merged**
